export const KafkaTopics = [
  "agent.task.created",
  "agent.task.accepted",
  "agent.task.completed",
  "agent.task.failed",
  "product.prd.approved",
  "architecture.hld.ready",
  "architecture.lld.ready",
  "engineering.task.accepted",
  "engineering.ui.generated",
  "engineering.backend.generated",
  "engineering.api_doc.generated",
  "engineering.frontend.completed",
  "engineering.android.completed",
  "engineering.ios.completed",
  "engineering.pr.created",
  "engineering.knowledge.updated",
  "quality.testing.started",
  "quality.testing.completed",
  "quality.bug.created",
  "devops.deployment.ready",
  "devops.deployment.completed",
  "devops.rollback.requested",
  "analytics.anomaly.detected",
  "analytics.report.generated",
  "analytics.rca.completed",
  "support.ticket.escalated",
  "security.finding.created",
  "approval.requested",
  "approval.completed",
  "incident.started",
  "incident.resolved",
  "knowledge.document.ingested",
  "memory.updated"
] as const;

export type KafkaTopic = (typeof KafkaTopics)[number];
